site_name: Text Analysis Documentation
nav:
  - Home: index.md
  - Install: install.md
  - Usage: usage.md

theme:
  name: material

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
